### ISSUE TITLE
Rename data/types to data/models

### ISSUE THREAD

**Issue by ivebencrazy** [Blanket-Warriors/BentoTime#11]
Original Title: "We should probably rename data/types to data/serializers?"
I think this is the most descriptive name for what these do.  Thoughts?

**Comment by ddrabik** [comment]
In my experience I have only seen serializers used to describe the conversion of an object in memory to a storable form, e.g. JSON.

I think models or adapters would be a more accurate name

**Comment by ivebencrazy** [comment]
oo yup I was mixing up serializers and adapters.  Makes sense in the name "serializer", too.  Adapter was the term I was looking for here.  But thinking about it more, maybe it's a good idea to name them as models.  This way we can feel more free to expand upon their prototypes in the future.  I feel like the name adapter implies that we just convert the data into a different form.

**Comment by ivebencrazy** [comment]
Resolved in https://github.com/Blanket-Warriors/BentoTime/pull/20
