### ISSUE TITLE
Move remaining code from Master branch into development branch

### ISSUE THREAD

**Issue by ivebencrazy** [Blanket-Warriors/BentoTime#12]
I think that we have mostly everything except for some stylesheet things.  Otherwise, I think we can force-push development into master very shortly.

**Comment by ddrabik** [comment]
I have been working off of the development branch, so nothing from my end

**Comment by ivebencrazy** [comment]
I believe we actually have everything we need from the master branch.  The only thing is an incomplete navbar.
