### ISSUE TITLE
Book Description displays escaped character codes

### ISSUE THREAD

**Issue by ivebencrazy** [Blanket-Warriors/BentoTime#21]
# Background

Currently, when looking at a Book View, our description text shows character codes instead of the correct characters.  This is assumably the straight text that is coming back from MangaEden's API.

# Steps to Reproduce
1. View any BookView page with a book description.

# Result
<img width="824" alt="untitled" src="https://cloud.githubusercontent.com/assets/8182843/13518948/d7fc9acc-e187-11e5-8439-3cb4ea8bbdc4.png">

# Expected
 - Text should display `"` instead of &quot;

# Needed

- [x] Replace the character codes with their correct characters
- [x] Make sure that this is not happening in other areas of the code

**Comment by ddrabik** [comment]
Another case where this is an issue:
"Bungaku Shoujo" to Oishii Recipe

<img width="1050" alt="screen shot 2016-03-13 at 6 22 45 pm" src="https://cloud.githubusercontent.com/assets/884377/13732914/bb20e1c4-e948-11e5-8a68-8a0a88ed87f5.png">

**Comment by ivebencrazy** [comment]
Is that in another language?  hahaha

**Comment by ddrabik** [comment]
Haha its supposed to be Japanese

<img width="1049" alt="screen shot 2016-03-13 at 6 30 01 pm" src="https://cloud.githubusercontent.com/assets/884377/13732976/a9bb7bfa-e949-11e5-94c9-7804ee19b598.png">

**Comment by ivebencrazy** [comment]
op

**Comment by ddrabik** [comment]
fixed in #24
