### ISSUE TITLE
Electron doesn't load 

### ISSUE THREAD

**Issue by ddrabik** [Blanket-Warriors/BentoTime#6]
BentoTime isn't loading when using npm run electron.
I suspect the build is not done before electron runs. 

I can work on it this week. I am thinking of using web pack dev server with browsersync as a proxy. Then the groundwork is set for hot module reloading

**Comment by ivebencrazy** [comment]
Yeah I've known this wasn't working, but hadn't gotten around to it.  Would be super helpful if you could do this!  :+1:

**Comment by ivebencrazy** [comment]
As a note, at our last meeting, we discussed that browsersync is probably not a good fit for this project, as webpack dev server can handle the things we need, and the mobile additions that browsersync brings are not really as useful in an electron app.

**Comment by ivebencrazy** [comment]
Closing this, as it is fixed in https://github.com/Blanket-Warriors/BentoTime/pull/22
